### ISSUE TITLE
📝 Clarify Regressors syntax

### ISSUE THREAD

**Issue by shnizzedy** [FCP-INDI/cpac-docs#54]
### Related problem

The example regressor config in the docs is

```YAML
nuisance_corrections:

  2-nuisance_regression:

    # this is a fork point
    #   run: [On, Off] - this will run both and fork the pipeline
    run: [On]

    # Select which nuisance signal corrections to apply
    Regressors:

      -  Name: 'default'

         Motion:
           include_delayed: true
           include_squared: true
           include_delayed_squared: true

         aCompCor:
           summary:
             method: DetrendPC
             components: 5
           tissues:
             - WhiteMatter
             - CerebrospinalFluid
           extraction_resolution: 2

         CerebrospinalFluid:
           summary: Mean
           extraction_resolution: 2
           erode_mask: true

         GlobalSignal:
           summary: Mean

         PolyOrt:
          degree: 2

         Bandpass:
           bottom_frequency: 0.01
           top_frequency: 0.1
           method: default

      -  Name: 'defaultNoGSR'

         Motion:
           include_delayed: true
           include_squared: true
           include_delayed_squared: true

         aCompCor:
           summary:
             method: DetrendPC
             components: 5
           tissues:
             - WhiteMatter
             - CerebrospinalFluid
           extraction_resolution: 2

         CerebrospinalFluid:
           summary: Mean
           extraction_resolution: 2
           erode_mask: true

         PolyOrt:
          degree: 2

         Bandpass:
           bottom_frequency: 0.01
           top_frequency: 0.1
           method: default
```

which doesn't include or explain all of the possible options

### Proposed feature

Update the documentation and/or the comments in the YAML to describe each possible key and value in a `Regressor` (and update the validation schema to match any newly described constraints)

### Acceptance criteria

- [ ] comments in default pipeline and/or description in docs
- [ ] updated validation schema (if applicable)
