### ISSUE TITLE
Eventually move schema to nodeblocks

### ISSUE THREAD

**Issue by sgiavasis** [FCP-INDI/cpac-docs#81]
I've added the [func_preproc.yaml](https://github.com/FCP-INDI/C-PAC/blob/new_docs/CPAC/func_preproc/func_preproc.yaml) (in the `new_docs` branch of the C-PAC repo) and wanted to get the discussion started on the `config:` level of these descriptors.

Eventually, it would be nice to move the schema logic (with defaults and available options) to the nodeblock descriptors, instead of in one global place.

But, we need to discuss and decide the best way to do this without cluttering the descriptor's layout and flow.
[Here is an example](https://github.com/FCP-INDI/C-PAC/blob/new_docs/CPAC/func_preproc/func_preproc.yaml#L16-L18) - in the `func_reorient` nodeblock, we can choose a grid orientation.

`RPI` is the default, but we have several options. It's not open-ended, because you can't pick any string of letters. So it would be nice to have a notation that documents the default (`RPI`), which, in the future, if the user does not specify this in their config, it will call on this descriptor YAML to auto-populate their decision as `RPI`.

Then, we would also like to have something like what I set up with `options:` although it doesn't have to stay the way I set it up. This could be a setup that simply enforces the possible options.

However, I haven't added any scaffolding for how we would document and enforce data type - this is something we'd have to handle from the schema as well.

**Comment by shnizzedy** [comment]
Updated idea, slightly modifying https://github.com/FCP-INDI/cpac-docs/issues/81#issuecomment-2794586112: instead of having one big schema with different reusable subschemas, we could give each schema its own file (which can each cross- or self-reference as needed), and then the example above could be like

```YAML
$schema: "http://json-schema.org/draft-07/schema#"
$id: "/CPAC/pipeline/schema/orientation"
description: >
  XYZ orientation of the image, where R = right, L = left, A = anterior,
  P = posterior, I = inferior, and S = superior
allOf:
  - type: string
  - enum:
      - RPI
      - LPI
      - RAI
      - LAI
      - RAS
      - LAS
      - RPS
      - LPS
```

for the schema and 

```YAML
Reorient BOLD:
  method:
    AFNI:
      config:
        desired_orientation: 
          default: RPI
          schema: /CPAC/pipeline/schema/orientation
```

to use it in a descriptor.

I wonder if it would make sense to have a flat structure for the reusable schemas (in which case we could drop the `pipeline/` level from the example above), to continue to differentiate between pipeline and data schemas, or to organize them in some other way?
