### ISSUE TITLE
Set up links to the nodeblock code/functions

### ISSUE THREAD

**Issue by sgiavasis** [FCP-INDI/cpac-docs#82]
In the new nodeblock descriptor YAML layout, we have the `source:` field which can list frameworks which implement and run execution of the pipeline nodes. For example, Nipype, NiWrap, etc.

The idea is to have [these fields](https://github.com/FCP-INDI/C-PAC/blob/new_docs/CPAC/func_preproc/func_preproc.yaml#L21-L22) link the descriptor's entry to the actual code.

At first I envisioned just a link to the actual lines in the Python files. However, this would have to be updated with each release, when we have it point to a specific tag. This could be automated, but that's not the only issue.

What is important for this design is to have it such that the functions implementing the nodeblocks in each and any of these frameeworks can be programmatically loaded in. So for example, maybe a link to the GitHub repository is not the best idea, and instead we can simply provide the path to the function itself. Anything that would make it easy for Python to import the function as an object later.

**Comment by shnizzedy** [comment]
I think we should just require

1. the descriptor is in a file with the same name (minus extension) as the nodeblock source code;
2. the descriptor file and the code file are siblings (in the same directory);

   and some requirement we define where

3. either the function name or the "name" in the Nodeblock decorator matches either the top-level key in the descriptor or that's what we fill in in the "source" field.

So for this example, we'd have 

```Python
@nodeblock(
    name="func_reorient",
    config=["functional_preproc", "update_header"],
    switch=["run"],
    inputs=["bold"],
    outputs=["desc-preproc_bold", "desc-reorient_bold"],
)
def func_reorient(wf, cfg, strat_pool, pipe_num, opt=None):
```

in `CPAC/func_preproc/func_preproc.py` and in `CPAC/func_preproc/func_preproc.yaml` we'd have 

```YAML
func_reorient:
    description:
        Reorients the header's grid to the chosen orientation.
        Highly recommended to run this nodeblock first in the BOLD pipeline. This is to ensure all data is set to the same grid orientation.
    references:
        None
    method:
        AFNI:
            description:
                Uses AFNI 3drefit -deoblique and 3dresample -orient.
            references:
                https://afni.nimh.nih.gov/pub/dist/doc/program_help/3drefit.html
                https://afni.nimh.nih.gov/pub/dist/doc/program_help/3dresample.html
            config:
                desired_orientation: RPI
                    options: [RPI, LPI, etc.]
            operations:
                graph TD;
            validation:
                s3://path/to/gold/standard
```

or

```YAML
Reorient BOLD:
    description:
        Reorients the header's grid to the chosen orientation.
        Highly recommended to run this nodeblock first in the BOLD pipeline. This is to ensure all data is set to the same grid orientation.
    references:
        None
    method:
        AFNI:
            description:
                Uses AFNI 3drefit -deoblique and 3dresample -orient.
            references:
                https://afni.nimh.nih.gov/pub/dist/doc/program_help/3drefit.html
                https://afni.nimh.nih.gov/pub/dist/doc/program_help/3dresample.html
            config:
                desired_orientation: RPI
                    options: [RPI, LPI, etc.]
            operations:
                graph TD;
            source:
                Nipype: func_reorient
            validation:
                s3://path/to/gold/standard
```

then all we have to keep synced is the filenames and the nodeblock names, and the CI can match them up automatically.
